proxy-groups:
    - { name: Proxy, type: select, proxies: [Proxy-manual, Proxy-test, Proxy-fallback] }
    - { name: Proxy-manual, type: select, proxies: *pg_default }
    - { name: Proxy-test, type: url-test, proxies: *pg_default }
    - { name: Proxy-fallback, type: fallback, proxies: *pg_default }
    - { name: GPT, type: fallback, proxies: *pg_GPT }
rules:
    - 'GEOIP,google,Proxy'
    - 'GEOSITE,google,Proxy'

    - 'GEOSITE,github,Proxy'

    - 'GEOSITE,youtube,Proxy'

    - 'GEOIP,telegram,Proxy'
    - 'GEOSITE,telegram,Proxy'

    - 'GEOIP,twitter,Proxy'
    - 'GEOSITE,twitter,Proxy'

    - 'GEOIP,netflix,Proxy'
    - 'GEOSITE,netflix,Proxy'

    - 'GEOIP,lan,DIRECT'
    - 'GEOIP,CN,DIRECT'
    - 'GEOSITE,cn,DIRECT'
    - 'GEOSITE,geolocation-!cn,Proxy'

    - 'MATCH,Proxy'
dns:
    enable: true
    ipv6: false
    listen: 0.0.0.0:7874
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter:
        - '+.local'
    default-nameserver:
        - 223.5.5.5
        - 223.6.6.6
    nameserver:
        - 223.5.5.5
        - 223.6.6.6
    nameserver-policy:
        "geosite:cn,private":
            - 223.5.5.5
            - 223.6.6.6
        "geosite:geolocation-!cn":
            - tls://8.8.4.4
            - tls://1.1.1.1
