proxy-groups:
    - { name: Proxy, type: select, proxies: [Proxy-manual, Proxy-test, Proxy-fallback] }
    - { name: Proxy-manual, type: select, proxies: *pg_default }
    - { name: Proxy-test, type: url-test, proxies: *pg_default }
    - { name: Proxy-fallback, type: fallback, proxies: *pg_default }
    - { name: GPT, type: fallback, proxies: *pg_GPT }
rules:
    - 'GEOIP,CN,DIRECT'
    - 'MATCH,Proxy'
dns:
    enable: true
    ipv6: false
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    listen: 0.0.0.0:7874
    nameserver:
        - 114.114.114.114
        - 119.29.29.29
    fallback:
        - tls://8.8.4.4
        - tls://1.1.1.1
    fallback-filter:
        geosite:
            - gfw
        domain:
            - '*.v2ex.com'
            - '*.metacubex.one'

            - '*.steamstatic.com'
            - '*.steamserver.net'
            - '*.steampowered.com'
            - '*.steamcommunity.com'

            - '*.github.com'
            - '*.githubusercontent.com'
            - '*.githubassets.com'

            - '*.google.com'
            - '*.google.com.hk'
            - '*.googleusercontent.com'
            - '*.googlevideo.com'
            - '*.googleapis.com'
            - '*.ggpht.com'
            - '*.youtube.com'
            - '*.ytimg.com'
